// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace DVDStore.DAL
{
    // NLog
    public partial class NLog
    {
        [Key, Column(Order = 1)]
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Machine name")]
        public string MachineName { get; set; } // MachineName (length: 200)

        [Required]
        [Display(Name = "Logged")]
        public DateTime Logged { get; set; } // Logged

        [MaxLength(5)]
        [StringLength(5)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Level")]
        public string Level { get; set; } // Level (length: 5)

        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Message")]
        public string Message { get; set; } // Message

        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Logger")]
        public string Logger { get; set; } // Logger (length: 300)

        [Display(Name = "Properties")]
        public string Properties { get; set; } // Properties

        [Display(Name = "Exception")]
        public string Exception { get; set; } // Exception

        public NLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
