// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReversePOCOTest
{
    public partial class UspGetListOfTitlesByCategoryReturnModel
    {
        public string title { get; set; }
        public string name { get; set; }
    }

}
// </auto-generated>
