// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DVDStore.DAL
{
    // NLog
    public partial class NLogMap : IEntityTypeConfiguration<NLog>
    {
        public void Configure(EntityTypeBuilder<NLog> builder)
        {
            builder.ToTable("NLog", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.Log").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.MachineName).HasColumnName(@"MachineName").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200);
            builder.Property(x => x.Logged).HasColumnName(@"Logged").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.Level).HasColumnName(@"Level").HasColumnType("varchar(5)").IsRequired().IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.Message).HasColumnName(@"Message").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.Logger).HasColumnName(@"Logger").HasColumnType("nvarchar(300)").IsRequired(false).HasMaxLength(300);
            builder.Property(x => x.Properties).HasColumnName(@"Properties").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Exception).HasColumnName(@"Exception").HasColumnType("nvarchar(max)").IsRequired(false);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<NLog> builder);
    }

}
// </auto-generated>
